### ISSUE TITLE
Packet error caused by uninstall

### ISSUE THREAD

**Issue by 6get-xiaofan** [RobertSkalko/Mine-And-Slash-Rework#1]
I'm using Mine And Slash 1.20.1. I want to stop using it because the translation is not sound. After I uninstall Mine And Slash and its API MOD, the archive shows a packet error prompt and does not support entering through safe mode. Can you provide repair support?

**Comment by RobertSkalko** [comment]
Ok  i figured it out. I think this will happen any time you remove a mod that adds a dimension.
So
Step1: install or place https://github.com/jaquadro/NBTExplorer/releases/tag/v2.8.0-win on your pc
Step2: open save/level.dat with it 
Step3: data/worldgensettings/dimensions:  delete the mmorpg:dungeon, save, done. 
World should load now. Idk if there are better ways of some mod that auto does this for you so tell me if there is

Also what language do you want a translation in?

**Comment by RobertSkalko** [comment]
Seems this is a minecraft datapack issue actually, makes sense because i registered the dimension with 1 or 2 json files
https://bugs.mojang.com/browse/MC-197860

**Comment by 6get-xiaofan** [comment]
Oh, I've already solved this issue. I used the NBTExplorer software to delete the world dimension related to the Dungeon, and then I was able to enter the world normally. I'm using Chinese. Compared to the previous versions, this version of Mine And Slash has undergone significant changes. I'm using the i18n MOD, which doesn't support the internationalization of the latest version of Mine And Slash. Thank you very much for your response.

**Comment by Rinorsi** [comment]
> Oh, I've already solved this issue. I used the NBTExplorer software to delete the world dimension related to the Dungeon, and then I was able to enter the world normally. I'm using Chinese. Compared to the previous versions, this version of Mine And Slash has undergone significant changes. I'm using the i18n MOD, which doesn't support the internationalization of the latest version of Mine And Slash. Thank you very much for your response.

I published the zh_cn file of 1.20.1 in the comment area of mine and slash in mcmod.cn, but it seems that there are many hard codes that lead to no translation. The Chinese-language file is comprehensive, at least it doesn't affect its use, although it has many flaws. You can get it if you need it.
我在mc百科的评论区放了1.20.1版本的zh_cn文件，尽管他有瑕疵，但是涵盖比较全面。但是模组存在很多硬编码导致没有办法全部翻译过来（而且有些属于硬翻译+润色），而且1.20.1缩水很多内容导致许多翻译只能臆测，因此它不完美，但是即使是不完美也依旧可用，你可以试试

**Comment by 6get-xiaofan** [comment]
> > Oh, I've already solved this issue. I used the NBTExplorer software to delete the world dimension related to the Dungeon, and then I was able to enter the world normally. I'm using Chinese. Compared to the previous versions, this version of Mine And Slash has undergone significant changes. I'm using the i18n MOD, which doesn't support the internationalization of the latest version of Mine And Slash. Thank you very much for your response.
> 
> I published the zh_cn file of 1.20.1 in the comment area of mine and slash in mcmod.cn, but it seems that there are many hard codes that lead to no translation. The Chinese-language file is comprehensive, at least it doesn't affect its use, although it has many flaws. You can get it if you need it. 我在mc百科的评论区放了1.20.1版本的zh_cn文件，尽管他有瑕疵，但是涵盖比较全面。但是模组存在很多硬编码导致没有办法全部翻译过来（而且有些属于硬翻译+润色），而且1.20.1缩水很多内容导致许多翻译只能臆测，因此它不完美，但是即使是不完美也依旧可用，你可以试试

So far, I do not plan to continue using the 1.20.1 version of MOD. I will wait for the i18n MOD update before considering using the 1.20.1 version of MOD, Thank you for your enthusiastic help!
