### ISSUE TITLE
Can there be more config or compatibility for the gun?

### ISSUE THREAD

**Issue by huntersxy** [RobertSkalko/Mine-And-Slash-Rework#103]
Hello, I'm wondering if there's a method to prevent a certain mod from being processed by MAS. I want to use the TAC-Z mod, but it doesn't deal any damage, and the "gear_compatibility" setting isn't effective.Perhaps gun mods are unable to inflict damage? I think.😔thank you.

**Comment by huntersxy** [comment]
Perhaps weapon mods ----->Perhaps gun mods

**Comment by RobertSkalko** [comment]
You can try making a custom base gear type and figuring out what damage type the gun does, and putting that in valid damage fields

**Comment by huntersxy** [comment]
i make a datapack,
![image](https://github.com/user-attachments/assets/e3ec2d3f-1e86-4c0f-b326-b26938795c0b)
but still no damage.
i upload datapack.
[tcmas.zip](https://github.com/user-attachments/files/16216490/tcmas.zip)
If you have the time, I hope you can help me out.
If it's just because the damage type is incorrect, please let me know that this is the reason.

**Comment by huntersxy** [comment]
Even if I filled in the data from the damage_type folder in tacz, it was to no avail.

**Comment by huntersxy** [comment]
https://github.com/MCModderAnchor/TACZ    is the tacz's github

**Comment by RobertSkalko** [comment]
Try turning  "tacz.bullet" into just tacz. remove the valid_proj_dmg_id

**Comment by RobertSkalko** [comment]
actually 
  target.hurt(user.damageSources().playerAttack(player), damage);

Seems they just use a normal player attack. Copy what swords do

**Comment by huntersxy** [comment]
thanks you!!!!!!!!!!!!!!it working now

**Comment by RobertSkalko** [comment]
Wow nice, that was quick edit

**Comment by huntersxy** [comment]
when i use "magnet" to get item,i found many null item😂
![image](https://github.com/user-attachments/assets/62c96936-403e-495f-aa53-2d470ef10b3f)

why

**Comment by RobertSkalko** [comment]
dmg particle, ignore lol

**Comment by RobertSkalko** [comment]
also don't use github issue as a way to offtopic chit chat.. Discord works better for that

**Comment by huntersxy** [comment]
ok

**Comment by waigoma** [comment]
Hello, I am also trying to use the same TAC-Z mod in a MAS environment. So I came across this issue, borrowed the data pack and modified with comments, but it did not work.

I would probably use Crafted Weapon Soul on the TAC-Z mod weapon so that it can be used in MAS, but it does not respond when I right click on it.

It would be great if you could let us know how you got it to work. Best regards. thank you.

--
If I'm asking this in the wrong place, I'd be grateful if you could point me in the right direction.

Sorry if my English is not correct. I am Japanese and have translated the text using DeepL translation.

my mods folder:
- curios-forge-5.9.1+1.20.1
- Library_of_Exile-1.20.1-1.4.7
- Mine_and_Slash-1.20.1-5.5.28
- tacz-1.20.1-1.0.2-release

**Comment by huntersxy** [comment]
@waigoma 
Have you modified 'saves\savename\serverconfig\mmorpg-server.toml' ?
Change `gear_comatibility=["minecraft: iron_stord: word"]` to `gear_comatibility=["minecraft: iron_stord: word", "tacz: modern_kinetic_gun: gun"]`

**Comment by waigoma** [comment]
@huntersxy  
I have not edit it...
I edit it and it works fine and has solved the problem!! Thank you very very much for your help!!!

**Comment by DazCarl** [comment]
@huntersxy yo bro how did you managed to get it work, i'm doing almost the same that you did but anything 
 can you help me

**Comment by huntersxy** [comment]
@DazCarl  Tell me your steps and let me analyze them

**Comment by DazCarl** [comment]
@huntersxy i downloaded the datapack put it in the server, eliminated the things that robert comment about valid_proj_dmg_id and change the other thing, edit the gear compatibilty but still didnt managed to get it work

**Comment by huntersxy** [comment]
@DazCarl You have corrected the damage_type，And modified mmorpg-server.toml，But still doesn't show the need for a soul?

**Comment by huntersxy** [comment]
@DazCarl I don't know why this also fails, but I think modifying the data package and files again, and restarting completely, may be effective

**Comment by Luisdar0z** [comment]
@huntersxy Sorry to revive this closed issue, but could you help me? I downloaded your datapack, modified the `gun.json` file that is in the `datapack/data/mmorpg/mmorpg_weapon_type `and left it like this:
```
{
  "can_dual_wield": true,
  "damage_validity_check": {
    "contains_in_dmg_id": [
      "bolt",
      "ammo",
      "bullet",
      "dart",
      "missile",
      "gun",
      "tacz.bullet"
    ],
    "source_check": "ANY",
    "tag_and_id_check": "MATCH_ANY"
    
  },
  "id": "gun",
  "isProjectile": true,
  "range": "RANGED",
  "style": "DEX"
}
```

Then I modified the mine_and_slash-server.toml file to add `"tacz:modern_kinetic_gun:gun"` in `gear_compatibility` and now I can add a soul to the weapon but I still can't deal damage to any enemy... Did I do something wrong or is there a step missing?"

**Comment by huntersxy** [comment]
change "tacz.bullet" to "tacz."



---Original---
From: ***@***.***&gt;
Date: Tue, Dec 3, 2024 00:59 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [RobertSkalko/Mine-And-Slash-Rework] Can there be more config orcompatibility for the gun? (Issue #103)




 
@huntersxy Sorry to revive this closed issue, but could you help me? I downloaded your datapack, modified the gun.json file that is in the datapack/data/mmorpg/mmorpg_weapon_type and left it like this:
 {   "can_dual_wield": true,   "damage_validity_check": {     "contains_in_dmg_id": [       "bolt",       "ammo",       "bullet",       "dart",       "missile",       "gun",       "tacz.bullet"     ],     "source_check": "ANY",     "tag_and_id_check": "MATCH_ANY"        },   "id": "gun",   "isProjectile": true,   "range": "RANGED",   "style": "DEX" }  
Then I modified the mine_and_slash-server.toml file to add "tacz:modern_kinetic_gun:gun" in gear_compatibility and now I can add a soul to the weapon but I still can't deal damage to any enemy... Did I do something wrong or is there a step missing?"

**Comment by huntersxy** [comment]
sorry ，is "tacz"，not "tacz."



---Original---
From: ***@***.***&gt;
Date: Tue, Dec 3, 2024 00:59 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [RobertSkalko/Mine-And-Slash-Rework] Can there be more config orcompatibility for the gun? (Issue #103)




 
@huntersxy Sorry to revive this closed issue, but could you help me? I downloaded your datapack, modified the gun.json file that is in the datapack/data/mmorpg/mmorpg_weapon_type and left it like this:
 {   "can_dual_wield": true,   "damage_validity_check": {     "contains_in_dmg_id": [       "bolt",       "ammo",       "bullet",       "dart",       "missile",       "gun",       "tacz.bullet"     ],     "source_check": "ANY",     "tag_and_id_check": "MATCH_ANY"        },   "id": "gun",   "isProjectile": true,   "range": "RANGED",   "style": "DEX" }  
Then I modified the mine_and_slash-server.toml file to add "tacz:modern_kinetic_gun:gun" in gear_compatibility and now I can add a soul to the weapon but I still can't deal damage to any enemy... Did I do something wrong or is there a step missing?"

**Comment by huntersxy** [comment]
if somebody download my zip，you need turn "tacz.bullet" to "tacz"
