### ISSUE TITLE
Can you tell me how to get all Rune

### ISSUE THREAD

**Issue by Lizchardt-sys** [RobertSkalko/Mine-And-Slash-Rework#105]
There is no tutorial to tell me how to get Rune, opening loot chests only gets Mos, Ita, Nos Rune

**Comment by RobertSkalko** [comment]
This is not an issue. Ask gameplay questions in the discord of modpack you're playing or the mns discord

For base mns, all runes are attainable from drops, some require killing higher lvl enemies
