### ISSUE TITLE
Suggestion: Vanilla HUD

### ISSUE THREAD

**Issue by TheSexyYeti** [RobertSkalko/Mine-And-Slash-Rework#110]
### Describe the bug you're experiencing

nothing happened. I just want to be able to revert the HUD back to the vanilla HUD. I'm working on a very large Modpack for 1.20.1. And I would love to have your mod in it. But I want to be able to retain the vanilla HUD. Is there no way you can add a config to change this?.

### Reproducability

read above Minecraft 1.20.2-5.5.27

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Tested Without Custom Mine and Slash Datapacks

- [X] In case I used Mine and Slash datapacks, I ran Mine and Slash in a new instance without custom datapacks and confirmed the bug still exists

### Mine and Slash version

none

### Logs

none

**Comment by RobertSkalko** [comment]
I'll add a NONE gui position option but are you sure you want mine and slash in your modpack? It's a combat overhaul mod and at the very least makes all other magic mods incompatible currently

**Comment by TheSexyYeti** [comment]
Yeah. I have no plans to add any other magic mods in my modpack anyways.

**Comment by RobertSkalko** [comment]
kk. Hm i need to add a feedback option for the issue templates

**Comment by RobertSkalko** [comment]
Is this still a problem? Irc i added the none gui position some time ago
