### ISSUE TITLE
[SUGGESTION]: disable starter gear & gear attribute chance

### ISSUE THREAD

**Issue by TheSexyYeti** [RobertSkalko/Mine-And-Slash-Rework#111]
### Tell us about your Suggestion

Can you added a config to disable the starter gear. And is there a way to make if so non mine and slash gear have a chance to spawn with mine and slash attributes. I know there's like a whole soul mechanic that allows you to add attributes to weapons and equipment. But I think there should be a chance for and item to spawn with them.

EDIT:
I literally just read the wiki saying something about a MNS stat compat data pack. how do I do this. or is there a archive of data packs that add compat?.

**Comment by RobertSkalko** [comment]
It's in config called start_items .. I'll rename that to GET_STARTER_ITEMS woops

For gear to spawn with mns stats, the datapack needed is auto item one, But you'd need to add every item. Generally you're meant to use soul extractors to move the stats around

**Comment by TheSexyYeti** [comment]
I can't seem to find that data pack anywhere when I do a search for it. I even use Perplexity to do a thorough search. And can't find it.

**Comment by TheSexyYeti** [comment]
I've notice that you have to manually change the "Get_Starter_Items" config on individual worlds that are already made. why isn't this option persistent across all new worlds automatically?.

**Comment by RobertSkalko** [comment]
Because the config is per world
