### ISSUE TITLE
[Bug]: Armor Per 10 Mana in Shaman Class does not count mana from the Balance ascendancy and is not affected by armor buffs

### ISSUE THREAD

**Issue by Shamadruu** [RobertSkalko/Mine-And-Slash-Rework#113]
### Describe the bug you're experiencing

As it says on the tin. The passive in the shaman spell school that provides armor per 10 mana does not count mana from the Balance ascendancy (and possibly other sources). With some testing it counted every other mana increase I tried. Further - and this may be intentional - the armor bonus is not affected by any percentage increase. Possibly relevant is that in Craft to Exile 2 the armor per 10 mana actually applies to energy instead.

In addition, the tooltips for the passive and Balance are both broken.

### Reproducability

Put points into the shaman armor per mana passive and the battlemage ascendancy to get Balance.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Tested Without Custom Mine and Slash Datapacks

- [X] In case I used Mine and Slash datapacks, I ran Mine and Slash in a new instance without custom datapacks and confirmed the bug still exists

### Mine and Slash version

v5.6.1

### Logs

https://gist.github.com/Shamadruu/e303ff3dec2acc3006fcc5a460cc7453

**Comment by RobertSkalko** [comment]
show the broken tooltips please

also that's by design, stats like "armor per mana" only use the base stats, they don't benefit each other

**Comment by RobertSkalko** [comment]
java.lang.ClassNotFoundException: com.robertx22.age_of_exile.mmorpg.MixinConnector

I checked the log because curious, wow. Gotta fix that

**Comment by RobertSkalko** [comment]
If someone still wants armor per mana and and stats like that to work differently, then I want an explanation of how exactly to do that.

There's a few problems here that I know of. Like, should 500 armor to mana benefit from armor %, mana %, both, neither?

If there's multiple stats like "5 mana per armor", "20% armor to mana" and "20% mana to armor", what should the exact order be?

Currently we have: 
- elemental stats and all attributes adding to other elements/attributes
- core stats that add other stats, and bonus stat per effect stacks
- more stat per other stat and % stat from other stat

**Comment by RobertSkalko** [comment]
Alright i tweaked how the stats are done, if it works it should benefit from % modifiers now
