### ISSUE TITLE
[SUGGESTION]: Section in the wiki to understand what the commands do and need as arguments

### ISSUE THREAD

**Issue by Shazway** [RobertSkalko/Mine-And-Slash-Rework#115]
### Tell us about your Suggestion

I want potatoes

And maybe a /mine_and_slash help command or more information on the commands in the wiki

**Comment by RobertSkalko** [comment]
What commands are confusing?

**Comment by RobertSkalko** [comment]
Closing because no answer. If some commands are confusing, state exactly which ones and exactly what's confusing about them
