### ISSUE TITLE
[SUGGESTION]: Entity blacklist

### ISSUE THREAD

**Issue by YaibaToKen** [RobertSkalko/Mine-And-Slash-Rework#116]
### Tell us about your Suggestion

Allow certain entity types to be blacklisted from getting levels.

**Comment by RobertSkalko** [comment]
Define "getting levels"

**Comment by YaibaToKen** [comment]
My bad, I'm referring to mobs being set to a specific level and their stats increased accordingly.
In my specific case, I'm using a mod called Digimod, that adds digimon and mechanics from some of the games, including their own levelling system, as such, a lvl1 digimon might actually be ridiculously strong due to having a higher mine and slash level, so I'd like to blacklist the digimon entity and have it completely removed from the mine and slash system.

**Comment by RobertSkalko** [comment]
Sorry that's not possible and not planned. But you can set their levels to be based on nearest player and also set this levels with commands when needed

**Comment by YaibaToKen** [comment]
Are you open to a PR adding a blacklist feature?

**Comment by RobertSkalko** [comment]
No.
