### ISSUE TITLE
[Bug]: Mine and Slash Datapack Check Failed

### ISSUE THREAD

**Issue by MrPoppinsReal** [RobertSkalko/Mine-And-Slash-Rework#117]
### Describe the bug you're experiencing

Every time Iam loaded into a world (even new create) it show a message: "Mine and Slash Datapack Error: 348 Jsons were marked as wrong with automatic error checking"

I've been read the log and also found out the issue, but I don't know how to fix :'<

### Reproducability

Idk, Iam just joining a world and its happens...

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Tested Without Custom Mine and Slash Datapacks

- [X] In case I used Mine and Slash datapacks, I ran Mine and Slash in a new instance without custom datapacks and confirmed the bug still exists

### Mine and Slash version

1.20.1 - 5.6.3

### Logs

https://gist.github.com/MrPoppinsReal/6fe4b763e1b23fc104096b4e344f3fee

**Comment by RobertSkalko** [comment]
Please post the entire log file next time

Btw this is just a new checking system and it reports possible problems. What seems to be happening is float max = Integer.MAX_VALUE  saves from 2147483650 to 2147483600 or something. Either way it's a non-issue but thanks for reporting

At least the few jsons I checked it was just that, you should be good

**Comment by PowderSol** [comment]
> Please post the entire log file next time
> 
> Btw this is just a new checking system and it reports possible problems. What seems to be happening is float max = Integer.MAX_VALUE saves from 2147483650 to 2147483600 or something. Either way it's a non-issue but thanks for reporting
> 
> At least the few jsons I checked it was just that, you should be good

Is there any way to temporarily hide this error? I'm having the same one and its cluttering my logs file

**Comment by RobertSkalko** [comment]
It should only do it once on start, i'll try fix so it doesn't produce this false positive

**Comment by AngleNaris** [comment]
Hi I also have this warning after update to latest version
But I didn't use any other datapack about Mine and Slash

**Comment by RobertSkalko** [comment]
can you send me your log? the new update should have fixed it

**Comment by AngleNaris** [comment]
> can you send me your log? the new update should have fixed it

OK, here
https://logpaste.com/fL6Z82QC

**Comment by RobertSkalko** [comment]
Oh i missed a thing. Ignore, will be fixed

**Comment by RobertSkalko** [comment]
Did the last update fix things?

**Comment by AngleNaris** [comment]
Yes, new version fixed this.
Thanks~
