### ISSUE TITLE
[SUGGESTION]: about scale_mob_to_nearby_player_lvl = true

### ISSUE THREAD

**Issue by AngleNaris** [RobertSkalko/Mine-And-Slash-Rework#118]
### Tell us about your Suggestion

Hello, I want to ask
is that config still working in latest version?
scale_mob_to_nearby_player_lvl = true
I find this is missing in the new config file
thanks.

**Comment by RobertSkalko** [comment]
It was removed, you can still set it but inside dimension datapacks

**Comment by AngleNaris** [comment]
Thanks , I will try to make a datapack

**Comment by RobertSkalko** [comment]
The reason the config was removed is because people found it confusing to have both a config and datapacks, i might re-add it if people want.
