### ISSUE TITLE
[Bug]: zombie drops mmorpg:invisible_item

### ISSUE THREAD

**Issue by gqrshy** [RobertSkalko/Mine-And-Slash-Rework#121]
### Describe the bug you're experiencing

I honestly don't know if this is reproducible, but the spawn zombies drop it from the spawner.
I suspect it is a buggy item, so I am reporting it just in case. Thanks again for all your development work.

I am Japanese, so I use machine translation.

### Reproducability

zombie spawner?

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Tested Without Custom Mine and Slash Datapacks

- [X] In case I used Mine and Slash datapacks, I ran Mine and Slash in a new instance without custom datapacks and confirmed the bug still exists

### Mine and Slash version

latest (5.7.3)

### Logs

https://gist.github.com/gqrshy/ce275c737514024135a641d55465f8cc

**Comment by RobertSkalko** [comment]
It's known. Those are invisible items used as damage "particles" for now. 

If clefal's PR is good, they will be replaced

**Comment by RobertSkalko** [comment]
Fixed in next update
