### ISSUE TITLE
[Bug]: buff continue to stack

### ISSUE THREAD

**Issue by Oscar0159** [RobertSkalko/Mine-And-Slash-Rework#122]
### Describe the bug you're experiencing

I upgraded my version from 1.20.1-v5.6.5 to 1.20.1-v5.7.3 and discovered this bug. I have not tested versions v5.7.0 to v5.7.2.

When a player swaps hands with an item (not an empty item) or runs, the buffs continue to stack, causing the magic shield, damage, resistance, etc., to reach very high values or their maximum limits.

![image](https://github.com/user-attachments/assets/41025d4f-4c95-4196-a0fe-f1929bae3b7f)
![image](https://github.com/user-attachments/assets/75893373-a054-407d-b452-96d7e5b1e23a)

### Reproducability

Quickly switch the player’s hand item using the scroll wheel or hotkeys.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Tested Without Custom Mine and Slash Datapacks

- [X] In case I used Mine and Slash datapacks, I ran Mine and Slash in a new instance without custom datapacks and confirmed the bug still exists

### Mine and Slash version

1.20.1-v5.7.3

### Logs

https://gist.github.com/Oscar0159/303baf017cfba68773b3f128d3a31c77

**Comment by RobertSkalko** [comment]
Hm i can't reproduce this one right now, are you on the mine and slash discord?

**Comment by Oscar0159** [comment]
yes

**Comment by RobertSkalko** [comment]
I'll drop a jar in #general , try if the bug still happens

**Comment by RobertSkalko** [comment]
Well found the reason, should be fixed next update https://github.com/RobertSkalko/Mine-And-Slash-Rework/commit/ad31a611ac7cbf2d1b95f939d5fa1778d45223d8 

The old system always produced new statcontexts on every gear calculation, so editing them was fine. New system caches them.. so editing is not good

**Comment by RobertSkalko** [comment]
Can you confirm the bug is fixed?

**Comment by Oscar0159** [comment]
bug fixed
