### ISSUE TITLE
Don't know how to set.

### ISSUE THREAD

**Issue by pingju555** [RobertSkalko/Mine-And-Slash-Rework#123]
actually 
  target.hurt(user.damageSources().playerAttack(player), damage);

Seems they just use a normal player attack. Copy what swords do

_Originally posted by @RobertSkalko in https://github.com/RobertSkalko/Mine-And-Slash-Rework/issues/103#issuecomment-2227299368_

**Comment by RobertSkalko** [comment]
Did you mean to reply in that thread or what?

**Comment by pingju555** [comment]
content in datapack added,damage type also changed , still doesn't work,seeing this place,don't know to set.

**Comment by pingju555** [comment]
1.mmorpg_base_gear_types，mmorpg_gear_slot，mmorpg_prophecy_modifier，mmorpg_weapon_type Both had the gun.json added.
2.sever config in saves ,weapon compatibility added Tacz:kenitc_gun as gun.
3.Copied damage type in Tacz,added to this_mod.jar also in damage type,  bullet.json is like this

```
{
  "exhaustion": 0.05,
  "message_id": "tacz.",
  "scaling": "never"
}
```
 Those are done,

in game,
gun is added correct gear souls,but still doesn't deal any damage to mob.

**Comment by RobertSkalko** [comment]
Send the datapack you made

**Comment by pingju555** [comment]
Thanks for tracking this issue,but the question is already not confuse me,for the following state:


In my modpack I made, a fatal error occurred, which makes no block can be interacted for some unknown reason,so this pack was abandoned,I don't play it anymore.


But for my part,it's pretty nice if you could make connection with the author of TacZ ,to make a compatibility pack between Mina and Slash And TacZ, also, a deeply modified modpack is also recommend,
with gun and dungeon,which is a good theme I think.


By the way, I could propose an idea that is mobs in dungeon will gain extra bullet resistance, and exploring dungeon will produce some key gun parts, and even more further,gun can only be assemble in specific workblock in MineAndSlash , also the affixes library of souls for guns also need to be upgraded,
for even more radical modification, mobs in dungeon could also use gun , which could be a funny patrt I think.&nbsp;


That's all,thanks for your patience to read this.



---Original---
From: "Robert ***@***.***&gt;
Date: Sun, Sep 29, 2024 22:50 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [RobertSkalko/Mine-And-Slash-Rework] Don't know how to set.(Issue #123)




 
Send the datapack you made

**Comment by RobertSkalko** [comment]
Np, but no need for any special compat from them, you just didn't setup the datapack correctly.. Anyway closing
