### ISSUE TITLE
[Bug]: Healing NPCs is basically impossible

### ISSUE THREAD

**Issue by DasBabyPixel** [RobertSkalko/Mine-And-Slash-Rework#126]
### Describe the bug you're experiencing

I tried to heal villagers, their health bar moved like 0.1%. Same with custom villagers, like MineColonies citizens.
This is especially a problem when (vanilla) damage is proportional, but healing isn't. Any damage done to a high level villager will take months to heal

### Reproducability

Summon a Villager, hit it with Instant Harming II, then Instant Health II. Harming does half of it's HP, health is useless.
Same with regeneration or other healing effects.

Also I lied with the mod up to date button, I'm on version 5.5.17, Craft to Exile 2 (0.6.2). Should this already be fixed in a newer version (or a bug in Craft to Exile 2), I'm happy to close this

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Tested Without Custom Mine and Slash Datapacks

- [X] In case I used Mine and Slash datapacks, I ran Mine and Slash in a new instance without custom datapacks and confirmed the bug still exists

### Mine and Slash version

5.5.17

### Logs

-

**Comment by RobertSkalko** [comment]
Mobs should be healing the same. Do they maybe count as players?

https://github.com/RobertSkalko/Mine-And-Slash-Rework/blob/2ea18608f366f57712f71d3591fcbf734a23b10a/src/main/java/com/robertx22/mine_and_slash/mixins/LivingEntityMixin.java#L48

This is where i lower vanilla healing for players only

**Comment by DasBabyPixel** [comment]
Turns out this is fixed in the newest version. Craft to Exile 2 just horribly out of date

**Comment by RobertSkalko** [comment]
I didn't say that, in fact i dont see any changes in the code at all here

**Comment by DasBabyPixel** [comment]
No, I tested. That fix was made in august, Craft to Exile is still on a version before that, just gonna have to manually update
Old version (Craft to Exile 2):
![grafik](https://github.com/user-attachments/assets/d1ea9164-4725-428c-b91e-078cb3387d47)
Latest version
![grafik](https://github.com/user-attachments/assets/748871ce-1865-4e44-a80a-ef92d3e2a218)
