### ISSUE TITLE
[Bug]: arphex mod items arent accepting gear souls

### ISSUE THREAD

**Issue by electroreal1** [RobertSkalko/Mine-And-Slash-Rework#128]
### Describe the bug you're experiencing

i tried to put an arphex gear soul on my stuff and it didnt take it

### Reproducability

get an arphex item try to put on a gear soul on it and it wont work

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Tested Without Custom Mine and Slash Datapacks

- [X] In case I used Mine and Slash datapacks, I ran Mine and Slash in a new instance without custom datapacks and confirmed the bug still exists

### Mine and Slash version

Mine_and_Slash-1.20.1-5.8.0

### Logs

https://gist.github.com/electroreal1/1d9a2b4e30bf0fac4dd737d829308290

**Comment by RobertSkalko** [comment]
If the item doesn't say it's missing a soul, then the auto compatibility didn't work, so you have to add it to gear_compatibility in mine_and_slash-server.toml serverconfig
