### ISSUE TITLE
[Bug]: Gear Souls Do Not Soul Items

### ISSUE THREAD

**Issue by varunax** [RobertSkalko/Mine-And-Slash-Rework#129]
### Describe the bug you're experiencing

1.20.1, fresh install latest Forge, NO ADDITIONAL MODS, NO CUSTOM DATAPACKS. Only latest MNS version.
When trying to soul an item with a gear soul, the item cannot be souled.

### Reproducability

Try to soul a weapon with any gear souls. Also, right clicking a gear soul does not produce a souled item.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Tested Without Custom Mine and Slash Datapacks

- [X] In case I used Mine and Slash datapacks, I ran Mine and Slash in a new instance without custom datapacks and confirmed the bug still exists

### Mine and Slash version

Latest

### Logs

N/A

**Comment by RobertSkalko** [comment]
Should be fixed in 5.8.1 when it's up
