### ISSUE TITLE
[Bug]: Newbie Gear Bag cannot be used.

### ISSUE THREAD

**Issue by YuNoGuy123** [RobertSkalko/Mine-And-Slash-Rework#130]
### Describe the bug you're experiencing

Normally when starting a world you get a newbie gear bag, you right click it, and it'll give you some starting gear. As of 5.8.0 this no longer works.

### Reproducability

Right click with newbie gear bag in hand.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Tested Without Custom Mine and Slash Datapacks

- [X] In case I used Mine and Slash datapacks, I ran Mine and Slash in a new instance without custom datapacks and confirmed the bug still exists

### Mine and Slash version

5.8.0

### Logs

https://gist.github.com/YuNoGuy123/ce24cf328bc27d07a3d0c72861dece57

**Comment by RobertSkalko** [comment]
Should be fixed in 5.8.1 when it's up

**Comment by YuNoGuy123** [comment]
Fixed, thanks!
