### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by meownight** [RobertSkalko/Mine-And-Slash-Rework#131]
### Describe the bug you're experiencing

load Instance dungeon will crash

### Reproducability

sometime the game will be crash ,then cant load Instance dungeon

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Tested Without Custom Mine and Slash Datapacks

- [X] In case I used Mine and Slash datapacks, I ran Mine and Slash in a new instance without custom datapacks and confirmed the bug still exists

### Mine and Slash version

Mine_and_Slash-1.20.1-5.5.17

### Logs

https://gist.github.com/meownight/ab50a7690e0d10e2440c84c7d0748eb2

**Comment by RobertSkalko** [comment]
Not sure why this is happening, lots of probably unrelated errors in the log, try removing more overlays mod

Also you're playing a modpack so ask for support there first

**Comment by meownight** [comment]
that modpack made by your team
name is CTE2

**Comment by RobertSkalko** [comment]
Sorry but not in CTE2's team, i just make 1 mod that modpack uses
