### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MiniQsERcE** [RobertSkalko/Mine-And-Slash-Rework#133]
### Describe the bug you're experiencing

It crashes when i enter the skill menu.
i tried it on zero mod it worked maybe cte2 have something idk

### Reproducability

just tap h and game crashed

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Tested Without Custom Mine and Slash Datapacks

- [X] In case I used Mine and Slash datapacks, I ran Mine and Slash in a new instance without custom datapacks and confirmed the bug still exists

### Mine and Slash version

Mine_and_Slash-1.20.1-v5.8.2

### Logs

https://gist.github.com/MiniQsERcE/f42df8b971581f65fc7e3eb101288cfc

**Comment by RobertSkalko** [comment]
Do not update mine and slash while playing modpacks with it, your datapacks broke. Wait for the modpack to update
