### ISSUE TITLE
[Bug]: Soul'ed Weapons cannot hit more than 1 mob

### ISSUE THREAD

**Issue by varunax** [RobertSkalko/Mine-And-Slash-Rework#134]
### Describe the bug you're experiencing

FRESH INSTALL, NO MODS, NO DATAPACKS.

When you soul a weapon like an Iron Sword with MNS stats, it can no longer damage more than 1 enemy. The base vanilla sword can still damage multiple enemies, but not a weapon with MNS stats. The animation for "hitting" will play, but still no damage will be done.

### Reproducability

Equip an Iron Sword with MNS stats, spawn 2-3 Zombies/Husk on the same block and attack them.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Tested Without Custom Mine and Slash Datapacks

- [X] In case I used Mine and Slash datapacks, I ran Mine and Slash in a new instance without custom datapacks and confirmed the bug still exists

### Mine and Slash version

LATEST

### Logs

N/A

**Comment by RobertSkalko** [comment]
This is probably because you're using a mod that overrides something combat related, like better combat or epic fight? I can't know because you didn't post a log

**Comment by varunax** [comment]
This is no additional mods, no additional datapacks, fresh install of MNS.

**Comment by RobertSkalko** [comment]
Oh you're right

**Comment by RobertSkalko** [comment]
Should be fixed in the next hotfix

**Comment by RobertSkalko** [comment]
Did the update fix it?

**Comment by varunax** [comment]
Fixed, thanks.
