### ISSUE TITLE
[Bug]: entering a map is instakill

### ISSUE THREAD

**Issue by Prejuicios** [RobertSkalko/Mine-And-Slash-Rework#135]
### Describe the bug you're experiencing

I started a new game very excited with a friend on a minecraft server in 1.20. 1, we leveled up to level 10 and got an adventure map, we built the map device and put the map we had found on it but when we entered we appeared dead, we tried multiple times and it was the same, we went into creative to recover our bodies (we used corpose mod) and not even in creative could we recover our things, when changing from creative to survival we died instantly too. Does anyone know how to fix that?

### Reproducability

Enter an adventure map

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Tested Without Custom Mine and Slash Datapacks

- [X] In case I used Mine and Slash datapacks, I ran Mine and Slash in a new instance without custom datapacks and confirmed the bug still exists

### Mine and Slash version

Mine_and_Slash-1.20.1-5.8.2

### Logs

<script src="https://gist.github.com/Prejuicios/3f50cbaa30df169d8fb920a971159279.js"></script>

**Comment by RobertSkalko** [comment]
What was the cause of death?

**Comment by gamediller** [comment]
I installed the first dungeon generator in the overworld, added a level 9 dungeon map, and created two escape pearls to enter the dungeon. However, as soon as I entered, I was killed instantly with a message saying I had exceeded the world boundaries. I attempted to recover my items, but it was not possible.

**Comment by RobertSkalko** [comment]
You might have some mod that messes with world borders

**Comment by gamediller** [comment]
I entered the dungeon at approximately x 100, y 100, z 100 and teleported to x 254584.500000, y 57.000000, z 158104.500000, which caused my character to die. I am currently trying to increase the world border to recover my items. If I succeed, I will get back to you.

**Comment by Prejuicios** [comment]
The only thing that comes out about death is:
[01:48:32 INFO]: Berthely left the confines of this world

I can go in and walk around in creative but when I go into survival it's like doing /kill

**Comment by RobertSkalko** [comment]
World borders shouldnt be a problem after this update, i hope
