### ISSUE TITLE
ideas 

### ISSUE THREAD

**Issue by gunfigterarusil** [RobertSkalko/Mine-And-Slash-Rework#138]
### Tell us about your Suggestion

Please modify the mob characteristics. Since mobs have levels, it's logical that they also have stats that affect their health, mana, and damage. Additionally, if they have mana, it would be logical for them to be able to use skills. I've conducted a few tests and found it relatively easy to make skills available based on mob levels.
Also, please add a weapon proficiency system. For example, if a player hits with a sword 100 times (even in the air), their sword proficiency level increases by 2. Subsequently, the required number of hits doubles. The damage dealt with this weapon increases based on the weapon proficiency level. However, if there was an agility characteristic, the attack speed could also be increased accordingly.
I have the most difficulty creating hidden skills that can be obtained by reading a book. I managed to make it so that the player receives additional skills by finding books in dungeons and using the book with right-click. However, there is a problem with mob intelligence. I don't know how to make them cast skills intelligently, as they usually spend all their mana on skills and then attack the player with their standard weapon.

**Comment by RobertSkalko** [comment]
Not planned
