### ISSUE TITLE
[Bug]: Summons not doing any damage to anything ( including hostiles)

### ISSUE THREAD

**Issue by Domino55555** [RobertSkalko/Mine-And-Slash-Rework#143]
### Describe the bug you're experiencing

Hostile mobs aren't taking damage by any  summons, they try to hit a mob , but they do no damage.
A video of the bug: https://drive.google.com/file/d/1khHrlfkvFSDyhEwq6VbJNPBKuYRZXgwP/view?usp=drive_link

### Reproducability

1º Spawn a mob, use a summon, watch it deal no damage, maybe a mod conflict?

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Tested Without Custom Mine and Slash Datapacks

- [X] In case I used Mine and Slash datapacks, I ran Mine and Slash in a new instance without custom datapacks and confirmed the bug still exists

### Mine and Slash version

Mine_and_Slash-1.20.1-5.8.3

### Logs

[cant upload log here, gives a timeout]

**Comment by RobertSkalko** [comment]
You have to actually set the vid to public

**Comment by RobertSkalko** [comment]
Also, do you actually have a weapon with soul in hand

**Comment by Domino55555** [comment]
sorry, it should be public now, also, I just use the staff to summon them, do I have to keep the weapon inhand or something of the sort?

**Comment by RobertSkalko** [comment]
Yes you do. Sorry might need to explain that somewhere but not sure where

**Comment by Domino55555** [comment]
yeah it works, thank you for the explanation!!
