### ISSUE TITLE
[Bug]: Shields Do Not Block

### ISSUE THREAD

**Issue by varunax** [RobertSkalko/Mine-And-Slash-Rework#151]
### Describe the bug you're experiencing

NO ADDITIONAL MODS, NO DATAPACKS

Shields do not block, do not play the blocking animation, nor do they lose durability.

### Reproducability

Equip a non-souled/souled shield.

Right click block.

Nothing happens as you're attacked.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Tested Without Custom Mine and Slash Datapacks

- [X] In case I used Mine and Slash datapacks, I ran Mine and Slash in a new instance without custom datapacks and confirmed the bug still exists

### Mine and Slash version

LATEST

### Logs

n/a

**Comment by RobertSkalko** [comment]
Use souled shields

**Comment by varunax** [comment]
> Use souled shields

Souled shields do not work either.

**Comment by RobertSkalko** [comment]
They work for me but no sound, ill fix that

**Comment by varunax** [comment]
Sounds works now, but shields don't lose any durability.
