### ISSUE TITLE
[SUGGESTION]: Blacklist Neat Bar For NPCs

### ISSUE THREAD

**Issue by norfaremc** [RobertSkalko/Mine-And-Slash-Rework#152]
### Tell us about your Suggestion

I would just like to be able to simplify or blacklist Neat bars for certain mobs. I love the Neat Bars, but I don't like that there's a "common" in front of their names. I think being able to fully disable the leveling system for certain mobs would be idea. Thanks!

**Comment by norfaremc** [comment]
I apologize, I see that there is a blacklist feature. However, having a way to rather blacklist mobs, but rather disable the leveling system from certain mobs would be best. With the NPCs blacklisted, their nametags no longer show... I'm assuming Neat Bars is needed for their nametags to show.

**Comment by norfaremc** [comment]
![Uploading image_2024-11-17_214248413.png…]()

**Comment by RobertSkalko** [comment]
You can disable mob lvling with entity datapacks and setting their max lvl to 1
