### ISSUE TITLE
[SUGGESTION]: Enfriamiento de la habilidad  de bardo ( ritardando ) 

### ISSUE THREAD

**Issue by danilopardo** [RobertSkalko/Mine-And-Slash-Rework#153]
### Tell us about your Suggestion

1) El enfriamiento de la habilidad es excesivo ya que es una de las 2 habilidades de daño del bardo debería poder tener la capacidad de usarse mas seguido ( jugando solo es demasiado alto el enfriamiento para sobrevivir ) 

2) el tipo de daño es incompatible con la idea de un bardo, no puede ser que la habilidad mágica de un bardo haga daño físico cuando la construcción de una clase exige tener alta inteligencia para el uso del mana 

3) en compensación para nivelar el juego, la habilidad podría consumir mas mana, así los jugadores tiene el mismo riesgo de usarla muy seguido y quedarse sin recursos y el enfoque a inteligencia debería se mas prioritario

**Comment by RobertSkalko** [comment]
Thanks but bard is the physical damage class, also english next time
