### ISSUE TITLE
[Bug]: Arrow button in menu dont work

### ISSUE THREAD

**Issue by Vuluxar** [RobertSkalko/Mine-And-Slash-Rework#156]
### Describe the bug you're experiencing

Arrow in menu Class dont work https://cdn.discordapp.com/attachments/1158389696234270832/1314287564605227101/2024-12-05_18-47-23.mp4

### Reproducability

Just press G to menu and click into Classes, then switch class and u cant go back by arrow button.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Tested Without Custom Mine and Slash Datapacks

- [X] In case I used Mine and Slash datapacks, I ran Mine and Slash in a new instance without custom datapacks and confirmed the bug still exists

### Mine and Slash version

0.8.0b

### Logs

https://gist.github.com/Vuluxar/1d5ba19bb14546bee87edcf45b18b0eb.js

**Comment by RobertSkalko** [comment]
This is a craft to exile 2 problem, isn't it?

**Comment by Vuluxar** [comment]
ah i guess, the menu is from craft to exile? if ye I will close it

**Comment by RobertSkalko** [comment]
The go back button is i think

**Comment by Vuluxar** [comment]
I cant check from what mod it is, if not from Mine and slash im sorry!

**Comment by Vuluxar** [comment]
![image](https://github.com/user-attachments/assets/ed97ce23-c803-4fa8-84b2-0f4118f6a02d) hm idk

**Comment by RobertSkalko** [comment]
Just report to cte2
