### ISSUE TITLE
[Bug]: spell casting bar is inconsistent

### ISSUE THREAD

**Issue by Margineanu6542** [RobertSkalko/Mine-And-Slash-Rework#157]
### Describe the bug you're experiencing

spell casting bar progresses visually when you pause till it ends but when you resume it goes back to the state that it was before pausing. It takes a few miliseconds to actually show the last state after the the casting time ends while it's paused and then unpaused. It also shows the spell going on cooldown while it's paused and goes back to available after the original casting time ends (the one that's not paused) (visual bug)

### Reproducability

1. Use a spell
2. Pause
3. Wait for it to end (optional)
4. Observe

### Mod up to date

- [x] Before submitting this issue I updated to the newest version and reproduced it

### Tested Without Custom Mine and Slash Datapacks

- [X] In case I used Mine and Slash datapacks, I ran Mine and Slash in a new instance without custom datapacks and confirmed the bug still exists

### Mine and Slash version

v.5.9.34

### Logs

there are no logs needed

**Comment by RobertSkalko** [comment]
Very niche but ill fix. I can't imagine anyone pauses game so often during casting that this is important but lol
