### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by CoconutsXXS** [RobertSkalko/Mine-And-Slash-Rework#160]
### Describe the bug you're experiencing

Crash on start with latest version of the mod, Forge and all of its dependencies...

### Reproducability

Create a new instance, download the 4 mods and launch.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Tested Without Custom Mine and Slash Datapacks

- [X] In case I used Mine and Slash datapacks, I ran Mine and Slash in a new instance without custom datapacks and confirmed the bug still exists

### Mine and Slash version

5.9.36

### Logs

https://gist.github.com/CoconutsXXS/6d20592ebfc4ce77f1e35827132df4fc

**Comment by RobertSkalko** [comment]
Turns out i did screw up something when i split my gradle stuff

**Comment by RobertSkalko** [comment]
Uploading new jars, tell me if it's fixed

**Comment by CoconutsXXS** [comment]
It works now! Thank you very much.

**Comment by RobertSkalko** [comment]
nice thanks
