### ISSUE TITLE
[Bug]: Haven't Chainmail Set in lang file

### ISSUE THREAD

**Issue by NHolicool** [RobertSkalko/Mine-And-Slash-Rework#161]
### Describe the bug you're experiencing

I try translate chainmail set of armor, try "mmorpg.tag.gear_slot.chainmail_chest", but it doesn't work.

### Reproducability

Add "mmorpg.tag.gear_slot.chainmail_chest" in lang file

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Tested Without Custom Mine and Slash Datapacks

- [X] In case I used Mine and Slash datapacks, I ran Mine and Slash in a new instance without custom datapacks and confirmed the bug still exists

### Mine and Slash version

5.9.34

### Logs

https://gist.github.com/NHolicool/f07ba6a7d3b87833ac717a3f2f0a2ab1

**Comment by RobertSkalko** [comment]
What is chainmail, a gear slot? Where is it not translated?

**Comment by RobertSkalko** [comment]
"mmorpg.gear_type.sword": "Sword",
"mmorpg.gearslot.sword": "Sword",
"mmorpg.tag.gear_slot.sword": "Sword",

here's sword for example and all the translations
