### ISSUE TITLE
[Bug]: vuln_crit stat is not working

### ISSUE THREAD

**Issue by adfa0107** [RobertSkalko/Mine-And-Slash-Rework#163]
### Describe the bug you're experiencing

I applied the physical_vuln_crit stat
![화면 캡처 2024-12-30 223818](https://github.com/user-attachments/assets/e2d0b70b-b7ad-4aaf-9bb0-bf0854a31d0f)

So I expected the basic attack and skill damage to come up as critical damage, but no critical applied
![화면 캡처 2024-12-30 223831](https://github.com/user-attachments/assets/12daeae1-4a17-4f08-9b03-cbaa0062caae)
![화면 캡처 2024-12-30 223955](https://github.com/user-attachments/assets/67e21392-f8ef-4667-946f-37f792729126)

Other vuln_cirt statistics were not applied either

### Reproducability

It happens when the physical_vuln_crit stat is applied as a command. No other method has been tested

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Tested Without Custom Mine and Slash Datapacks

- [X] In case I used Mine and Slash datapacks, I ran Mine and Slash in a new instance without custom datapacks and confirmed the bug still exists

### Mine and Slash version

Mine_and_Slash-1.20.1-5.9.37

### Logs

https://gist.github.com/adfa0107/104b1f8db6c20da3533bfc798450d7d6

**Comment by RobertSkalko** [comment]
that stat is about making you always take dmg as crits, not you dealing crits

**Comment by adfa0107** [comment]
Sorry for opening issue without understanding the feature, thank you for your response.
