### ISSUE TITLE
Is it possible to add souls to items with special functions by right-clicking, or is it not compatible properly?

### ISSUE THREAD

**Issue by 3350789wdes** [RobertSkalko/Mine-And-Slash-Rework#22]
I tried to add a sword from Cataclysm to be compatible, but it didn't work at all, and it could be that I did it wrong.

**Comment by RobertSkalko** [comment]
How am i supposed to know how to help you

**Comment by RobertSkalko** [comment]
For help with setting up datapacks, use the discord
