### ISSUE TITLE
The GemItem could not be translated

### ISSUE THREAD

**Issue by TUsama** [RobertSkalko/Mine-And-Slash-Rework#25]
here is the pic:
![image](https://github.com/RobertSkalko/Mine-And-Slash-Rework/assets/21279092/b2e5dc27-ae3d-4530-bd73-20ac1a1c25f3)

but the formatter of GemRank and GemName works fine.

Also, I wanna ask if there is a plan to replace all hard-coding content with translatable texts. For now there are too many untranslatable strings in the mod, and some of them are so important for the gameplay. It would be wonderful for the non-speaking English players to enjoy your mod with a more immersive game experience.

**Comment by RobertSkalko** [comment]
I typically replace hard coded text after a while when i have nothing else to do, in next update there'll be some fixes to this

**Comment by TUsama** [comment]
that helps A LOT. Thanks!
