### ISSUE TITLE
Disable capability

### ISSUE THREAD

**Issue by entyen** [RobertSkalko/Mine-And-Slash-Rework#34]
I need make only items on CTE2 Essentials works as Mine and Slash armor and only this armor can convert on Crafted Souls, I can do it on datapak or settings?

**Comment by RobertSkalko** [comment]
What's the problem exactly

**Comment by RobertSkalko** [comment]
That's not supported currently as i don't see a reason, but you could try putting "" in compat item config and see if that makes it stop working as a mns armor

**Comment by entyen** [comment]
not working:( okay

**Comment by entyen** [comment]
it's needed because i can make item like this it's not good i think no durability items imbalance
![image](https://github.com/RobertSkalko/Mine-And-Slash-Rework/assets/31936997/b64388b9-7d2a-4aa9-b98d-76a0cf9ec653)

**Comment by RobertSkalko** [comment]
Added to next update, now any invalid gear type will set the item to have no type
