### ISSUE TITLE
[Suggestion] Config to remove weapon restrictions

### ISSUE THREAD

**Issue by MrKashew** [RobertSkalko/Mine-And-Slash-Rework#4]
Rather than adding individual weapons, perhaps a config to allow all weapons to work? Hence scaling damage taken by mob - what are your thoughts

**Comment by RobertSkalko** [comment]
Seeing as you had some bug that caused half the mod to stop working, after checking out what the working mod looks like, is this still relevant?

**Comment by MrKashew** [comment]
So when running the mod solo I still don’t see requirements for say a Vanilla Sword (whether it is configured or not) despite seeing the Wepaon Requirements not met popup, but do see requirements from weapons in this mod. Is this intended behavior still?

**Comment by RobertSkalko** [comment]
Ah i see, yes. You do need a weapon with mine and slash stats to cast spells

**Comment by RobertSkalko** [comment]
I forgot to mention if you hate some spells that require a certain weapon, like arrow barrage needing a bow, you can always edit the spell datapack to not require it, but having MNS stats is a must. 

Closing unless you want to continue.
