### ISSUE TITLE
5.3.8 Attack Speed

### ISSUE THREAD

**Issue by entyen** [RobertSkalko/Mine-And-Slash-Rework#48]
I have bug don't know how i can fix it 

/data/mmorpg/mmorpg_stat/attack_speed.json

`{
  "data": {
    "attribute_id": "minecraft:generic.attack_speed",
    "base": 0.0,
    "ele": "Physical",
    "id": "attack_speed",
    "max": 2.14748365E9,
    "min": -1000.0,
    "name": "Attack Speed",
    "perc": true,
    "scale": "NONE",
    "uuid": "dce362b7-d1b1-4f90-ad6d-024ffcf0b58a"
  },
  "ser": "vanilla_attribute_stat_ser"
}`

after update this stat on my datapack make server errors on launch.

[crash-2023-12-28_23.00.02-server.txt](https://github.com/RobertSkalko/Mine-And-Slash-Rework/files/13789331/crash-2023-12-28_23.00.02-server.txt)

**Comment by RobertSkalko** [comment]
I'll push a fix soon
