### ISSUE TITLE
Mine-And-Slash 1.20.1

### ISSUE THREAD

**Issue by huudongoc** [RobertSkalko/Mine-And-Slash-Rework#56]
In 1.20.1 players who want to fight must run out of new fitness bars except for other players' blood

**Comment by RobertSkalko** [comment]
Can you better explain what you are asking for? I'm confused

**Comment by huudongoc** [comment]
you watch the video I shot here [Link Video](https://saodoeduvn-my.sharepoint.com/:v:/g/personal/2000094_saodo_edu_vn/EdokU-kZanBDic3G__gkpg8BPBwHP04oCKWtwfgNKk8eVg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=f8hRmE). When entering the game when 2 players fight, there will be no damage.Only when the fitness bar runs out will the player be able to deal damage to the opponent. I think it's an error

**Comment by RobertSkalko** [comment]
Ah i get it. Yeah that's with the auto group config enabled by default, mine and slash prevents damage because you are considered group. 

But yes the part when the dmg happens when 0 energy is a bug, will fix

**Comment by huudongoc** [comment]
can I fix i

**Comment by RobertSkalko** [comment]
world/serverconfig/mmorpg-server.toml > all_players_are_allied = false

**Comment by huudongoc** [comment]
thanks u

**Comment by huudongoc** [comment]
I did as you showed me. But it gets less damage and only when it runs out of physical strength does it get more damage.I look forward to you fixing it in your next update <3

**Comment by RobertSkalko** [comment]
Yes the more damage is because of a bug, that will be fixed
