### ISSUE TITLE
Suggestion Compatibility

### ISSUE THREAD

**Issue by Aabaddon** [RobertSkalko/Mine-And-Slash-Rework#6]
Would be nice to add compatibility with iron´s spells and spellbooks replacing the mana system and the wands with the other mod ones

**Comment by RobertSkalko** [comment]
Pretty sure it's impossible, but what would you consider i do to make things compatible?

**Comment by gunfigterarusil** [comment]
My English very bad, sorry, i write Ukrainian.
Я думав над цим питанням, коли пробував ваш мод переробити аби він давав всю магічну систему із гри Skyrim, особливо механіку яка давала вивчення нових заклять прочитавши книгу, але без вашої допомоги я не знаю як це зробити.
Maybe you can help.
