### ISSUE TITLE
1.20.1 Mine and Slash leveling bug.

### ISSUE THREAD

**Issue by SavageKiller13** [RobertSkalko/Mine-And-Slash-Rework#65]
Playing on latest mod version of 1.20.1 (v5.3.16); I have found a bug related to husbandry and leveling items. 
What happened is I was breeding animals and when I would switch to my sword (which had level 3 before this) it gained levels. After a couple minutes of breeding animals the sword got up to level 15. I tested this with other MnS tools and it had the same effect.

**Comment by RobertSkalko** [comment]
That should be normal. Swords are considered husbandry tool. And your sword isn't gaining gear levels, it's gaining tool levels
