### ISSUE TITLE
Question about a mod

### ISSUE THREAD

**Issue by revmehard** [RobertSkalko/Mine-And-Slash-Rework#71]
Hey Robert,

sorry for posting about sth else here but wasn't sure how to contact you elsewhere.
I found this: https://www.nexusmods.com/titanquestanniversaryedition/mods/7
Would you be able to update this mod for the newest titan quest version + new DLCs so it works there as well?
Any way to contact you privately for this? I'd be happy to pay you to make this happen.

Thanks very much in advance!
My discord name: larac9

**Comment by RobertSkalko** [comment]
hey sorry i don't really play titan quest rn

**Comment by RobertSkalko** [comment]
Uh i made it with this i think https://github.com/RobertSkalko/Grim-Dawn-Modding-Tool

**Comment by RobertSkalko** [comment]
Answered so closing. Unless they drastically changed the file formats, the tool should be able to generate random affix mod. Might need a slight code tweak, I don't remember if I modded grim dawn or TQ last time i updated the tool
