### ISSUE TITLE
Please Add Option to Turn Off Chat Warnings

### ISSUE THREAD

**Issue by Quest79** [RobertSkalko/Mine-And-Slash-Rework#72]
Enjoying this mod so far. I have bound my main attack to my right mouse button. This is comfortable and everything is fine. I do not want to bind it to another key.

This however gets annoying
[https://i.imgur.com/UajJgva.png](https://i.imgur.com/UajJgva.png)

**Comment by RobertSkalko** [comment]
will be added in next update

**Comment by RobertSkalko** [comment]
Added
