### ISSUE TITLE
All maps have negative experience

### ISSUE THREAD

**Issue by Proxwian** [RobertSkalko/Mine-And-Slash-Rework#73]
Any way to tweak this? Also damage is too high, player can die in one hit and loose their level, making Maps very unprofitable

**Comment by RobertSkalko** [comment]
mob dmg will be lowered probably but minus xp in maps is intended because they have such massive pack size and are 10 times better to grind

**Comment by Proxwian** [comment]
Solved with datapack dimension config. But items still would have negative exp multiplier, which can confuse players :(
