### ISSUE TITLE
[1.20.1] Invulnerable mobs

### ISSUE THREAD

**Issue by Proxwian** [RobertSkalko/Mine-And-Slash-Rework#78]
Most of spells and perks do .00x damage that sometimes can make mobs invulnerable. Mobs health stuck at ~1% and never drops below. Physical damage from weapons is good btw, but still can't kill mobs with broken HP from spells.

[latest.log](https://github.com/RobertSkalko/Mine-And-Slash-Rework/files/14626776/message.txt)

**Comment by RobertSkalko** [comment]
What spells do 0 dmg

**Comment by Proxwian** [comment]
I mean spells can do x.00x damage, for example 43.009

**Comment by Proxwian** [comment]
After that, mobs become invulnerable, because mod can't properly work with these numbers

**Comment by RobertSkalko** [comment]
This should be fixed in latest library of exile
