### ISSUE TITLE
[1.20.1] Different maps same dungeons

### ISSUE THREAD

**Issue by Proxwian** [RobertSkalko/Mine-And-Slash-Rework#79]
On my server, I give player maps as rewards with command /mine_and_slash give map {Player} random

Some player noticed that they can be teleported in dungeon, in which they were before (even the map id is different).

There's enough place to create new dungeon in mmorpu:dungeon world

**Comment by RobertSkalko** [comment]
on an old enough server thats possible. reset the map world folder. If this is a new server, and it happened more than once, then i'll check, maybe the radius is too small

**Comment by RobertSkalko** [comment]
Couldn't reproduce
