### ISSUE TITLE
1.20 some issues

### ISSUE THREAD

**Issue by ddaodan** [RobertSkalko/Mine-And-Slash-Rework#8]
Thank you for updating this mod to 1.20. I encountered some issues while playing with my friends:

1. The adventure map doesn't generate completely, causing monsters to spawn only once.
2. There is no guidebook, so players who haven't played the old version don't know how to get started.
3. The language files are incomplete, and my friends aren't fluent in English, so they don't understand many of the texts. Also, there are places where key names appear.
4. In the adventure map, there's an area that cannot be accessed. Its entrance is blocked by two blocks of sand.
5. Some areas in the adventure map have generation issues, either appearing in an inaccessible location or with one or more rooms missing.

If you're willing to address these issues, I can offer my assistance.

**Comment by hron84** [comment]
+ no keybinds are registered to the controls gui, so I dunno what keypress needed for e.g. talent tree

**Comment by RobertSkalko** [comment]
There's no keybind for talents, only for main hub, the hub contains all the buttons to access talents.

**Comment by RobertSkalko** [comment]
Monsters should spawn only once, unless i missunderstood. Localization is being updated over updates, map generation bug should have been fixed but I don't remember in what update exactly. I'll close, open separate issues for problems that are still ongoing
