### ISSUE TITLE
Weird translation and seed icons

### ISSUE THREAD

**Issue by SaloEater** [RobertSkalko/Mine-And-Slash-Rework#81]
The English translations says:
`"block.mmorpg.harvest.purple": "Chaotic Seeds",
"block.mmorpg.harvest.green": "Primal Seeds",
"block.mmorpg.harvest.blue": "Lucid Seeds",`

The code says:
`static String BLUE_NAME = "Lucid";
static String PURPLE_NAME = "Chaotic";
static String GREEN_NAME = "Primal";`

Their actual names in game doesn't match their translations:
<img width="343" alt="Screenshot 2024-03-18 at 6 52 50 PM" src="https://github.com/RobertSkalko/Mine-And-Slash-Rework/assets/6031470/87a0a1c8-e682-483c-b98f-83a347f8fa21">
<img width="343" alt="Screenshot 2024-03-18 at 6 52 47 PM" src="https://github.com/RobertSkalko/Mine-And-Slash-Rework/assets/6031470/2fbfc044-934d-4ee7-a236-10a5990fb6d3">
<img width="343" alt="Screenshot 2024-03-18 at 6 52 44 PM" src="https://github.com/RobertSkalko/Mine-And-Slash-Rework/assets/6031470/e09b4f76-c21d-4d62-97e4-1fcc58892037">

**Comment by RobertSkalko** [comment]
Closing because these items don't exist now
