### ISSUE TITLE
Animals in Minecarts

### ISSUE THREAD

**Issue by Spinsz** [RobertSkalko/Mine-And-Slash-Rework#82]
There is an issue where minecarts instantly derail with an animal in it. Animal hops in the minecart and as soon as the minecart moves, it derails.

**Comment by RobertSkalko** [comment]
does this still happen without mns

**Comment by Spinsz** [comment]
No, it doesn't. Only on MNS. Sadly.

**Comment by RobertSkalko** [comment]
How do i test this? Can i see a screenshot of your setup and what do you mean by derail?

I tried by putting  a zombie in a cart and it moved fine

**Comment by Spinsz** [comment]
I put an animal in the cart, tried to push it. As soon as it starts moving
the cart derails and breaks. I don't have any screen shots at the moment,
sorry.

**Comment by RobertSkalko** [comment]
Closing as can't replicate
