### ISSUE TITLE
Tp back portal item not working.

### ISSUE THREAD

**Issue by AngleNaris** [RobertSkalko/Mine-And-Slash-Rework#84]
Mine_and_Slash-1.20.1-5.3.22
forge 47.2.20
other 170 mods.
-------------------------------
There is no error in log.

use tp back portal item can't tp outside the adventure map

**Comment by AngleNaris** [comment]
It's on server.

**Comment by AngleNaris** [comment]
Oh I found something in log, When use the back portal, there is this line in log:
No world with id: minecraft:

**Comment by RobertSkalko** [comment]
post the entire log

**Comment by AngleNaris** [comment]
[https://logpaste.com/zK7IB6It](url)
Here is the full log.
It probably happened in 17:32 
Thanks

**Comment by AngleNaris** [comment]
[https://logpaste.com/zK7IB6It](https://logpaste.com/zK7IB6It)
Here is the full log.
It probably happened in 17:32
Thanks

**Comment by RobertSkalko** [comment]
cant find the No world with id: minecraft:

from your last message in this log

**Comment by AngleNaris** [comment]
Yeah I found that " id: minecraft:" thing only appear in my MC server soft console ( it's a tool for manage mc servers )
I will do some tests to confirm that issue ( use Mine and Slash only )
Thanks.

**Comment by AngleNaris** [comment]
OK, I know what the problem is.
If I put the map device in overworld, the tp portal works fine.
But when I placed it in other dimension, such as mirror overworld mod's dimension
Tp portal can't let me leave the map.
