### ISSUE TITLE
Auto Salvage Bag not auto salvaging?

### ISSUE THREAD

**Issue by SirMoogle** [RobertSkalko/Mine-And-Slash-Rework#90]
Currently playing the Craft to Exile - Dissonance pack, and I crafted an Auto Salvage Bag. I set it to salvage common gear, but it still shows up in my inventory. Am I doing something wrong?

**Comment by RobertSkalko** [comment]
Equip it to curio slot irc

**Comment by SirMoogle** [comment]
Alright, I've equipped it to the curio slot. I think what I'm confused on is that it doesn't seem to salvage equipment that I find in chests or that I drop from my inventory, and where the salvaged materials go.

**Comment by RobertSkalko** [comment]
It salvages when you pick them up from the ground. The materials are probably in your master bag

**Comment by SirMoogle** [comment]
Played around a bit more and it seems that the exceptions it makes is gear that you'd normally find in vanilla, like helmets, chestpieces, leggings, and boots; vanilla swords also seem to be affected. Anyway to get those to automatically salvage or is that intended?

**Comment by RobertSkalko** [comment]
If the gear has no mine and slash stats it wont be salvaged

**Comment by SirMoogle** [comment]
The issue still persists after exiting and reopening the inventory so that the gear has stats. When I toss it and pick it up, it shows up again in my inventory.

**Comment by RobertSkalko** [comment]
The auto salvage is simple, if it's setup to salvage say common rarity, it will salvage any gear with mns stats that has common rarity, unless that item is enchanted. Closing as this isn't an issue and also not a latest version question

**Comment by SirMoogle** [comment]
Could you add documentation stating that for whichever version is on MC 1.15.2 that enchanted items don't get salvaged? Nowhere in either repository is this mentioned.
