### ISSUE TITLE
Clean up unused textures

### ISSUE THREAD

**Issue by Ezoteric** [RobertSkalko/Mine-And-Slash-Rework#92]
Could you please clean up unused textures as i am making a texturepack for BDcraft and i noticed that there are textures not used.
I noticed a entity directory but i havent seen these spawn anywhere.
Would really appreciate that non used were removed or a list so i know which ones are not used.

Thnx in advance.

**Comment by RobertSkalko** [comment]
What's bdcraft? Think i removed all in next update, it was just a few currency icons and some chest textures
