### ISSUE TITLE
look... he remove bee salvage and have problem

### ISSUE THREAD

**Issue by halk6000** [RobertSkalko/Mine-And-Slash-Rework#93]
![2024-05-22_19 29 03](https://github.com/RobertSkalko/Mine-And-Slash-Rework/assets/45394417/dad23002-d01e-44b3-8026-15005546daee)

**Comment by RobertSkalko** [comment]
What even is this?

**Comment by halk6000** [comment]
error synergy. mod mine and slash add recipe to productive bee ,,salvage bee" 4.7.2 but now update this to latest version and this bee dont have. so if play on single player we dont have problem but if try play try multi so perrson when connect have this comunicate. and dont connected. forge 47.2.0 and can download pack too see problem. your mod is great, but it's in quarantine for now because it causes problems. i remove it so fix problem.

**Comment by RobertSkalko** [comment]
mine and slash does not add bee

**Comment by halk6000** [comment]
yea so look in pack. besides, the java reference path matches the mmorpg nomenclature, check the classes to see if you have any stupid references.
but I bet it's about the name salvage station mod production bee thinks it's salvage so he made a bee. although it's strange because in version 4.7.2 of your mod it added this bee normally but there were no recipes in it, you could play multiplayer normally, now the lack of recipes for this bee is causing a problem.

**Comment by RobertSkalko** [comment]
Is this cte2 modpack? do not update mine and slash yourself

**Comment by halk6000** [comment]
nope :) AkinoxPL my pack

**Comment by RobertSkalko** [comment]
Closing due to unresolved confusion
